import Head from 'next/head'
import { useState } from 'react'
import { Alert, Button, Container, Grid, Snackbar, Stack } from '@mui/material';
import { getMainPage } from '../services/api'
import Image from 'next/image'
import LinkedIn from '@mui/icons-material/LinkedIn';
import Github from '@mui/icons-material/Github';

const Home = ({ blogData }) => {
  const full = 425
  const middle = 150
  const xsMargin = 16
  const mMargin = 32
  const lgMargin = 64
  return (
    <div>
      <Head>
        <title>Guillaume Duhan - Développeur Front-End Javascript</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container className={'animate__animated animate__fadeIn'} style={{ maxWidth: 1000, marginTop: mMargin }}>
          <center>
            <Grid style={{ marginTop: lgMargin }}>
              {/* <Image src="/second.png" alt="me" width={middle} height={middle} /> */}
              <Image src="/main.png" alt="me" width={full} height={full} />
              {/* <Image src="/third.png" alt="me" width={middle} height={middle} /> */}
            </Grid>
            {blogData && blogData.map((x) => {
              const Component = x.component
              return <Component>{x.content}</Component>
            })}
            <footer style={{ marginTop: xsMargin }}>
              <a href="https://www.linkedin.com/in/guillaumeduhan/" target="_blank">
                <LinkedIn color={'primary'} style={{ margin: xsMargin }} />
              </a>
              <a href="https://github.com/guillaumeduhan" target="_blank">
                <Github color={'primary'} style={{ margin: xsMargin }} />
              </a>
              <Stack justifyContent="center" alignItems="center" direction="column" spacing={2}>
                <Button variant="contained" href="https://www.malt.fr/profile/guillaumed">Me recruter sur Malt</Button>
              </Stack>
            </footer>
          </center>
        </Container>
      </main>
    </div >
  )
}


export async function getStaticProps({ params }) {
  const blogData = await getMainPage()
  return {
    props: {
      blogData
    }
  }
}

export default Home