import Head from 'next/head'
import { Button, Container, Grid, Stack } from '@mui/material';
import { getMainPage } from '../services/api'
import Image from 'next/image'
import Link from 'next/link'

const Home = ({ blogData }) => {
  const full = 425
  const xsMargin = 16
  const mMargin = 32
  const lgMargin = 64
  return (
    <div>
      <Head>
        <title>Guillaume Duhan - Développeur Front-End Javascript</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container className={'animate__animated animate__fadeIn'} style={{ maxWidth: 1000, marginTop: mMargin }}>
          <center>
            <Grid style={{ marginTop: lgMargin }}>
              <Image src="/main.png" alt="me" width={full} height={full} />
            </Grid>
            {blogData && blogData.map((x, i) => {
              const Component = x.component
              return <Component key={i}>{x.content}</Component>
            })}
            <footer style={{ marginTop: xsMargin }}>
              <Stack justifyContent="center" alignItems="center" direction="column" spacing={2}>
                <Button variant="contained" onClick={() => {
                  window.open('https://www.malt.fr/profile/guillaumed', '_blank')
                }}>Me recruter sur Malt</Button>
              </Stack>
              <Stack style={{ marginTop: xsMargin }} justifyContent="center" alignItems="center" direction="row" spacing={2}>
                <div>
                  <Link href="https://www.linkedin.com/in/guillaumeduhan/">
                    <Image src="/linkedin.png" alt="me" width={mMargin} height={mMargin} />
                  </Link>
                </div>
                <div>
                  <Link href="https://github.com/guillaumeduhan">
                    <Image src="/github.png" alt="me" width={mMargin} height={mMargin} />
                  </Link>
                </div>
              </Stack>
            </footer>
          </center>
        </Container>
      </main>
    </div >
  )
}


export async function getStaticProps({ params }) {
  const blogData = await getMainPage()
  return {
    props: {
      blogData
    }
  }
}

export default Home